
const BOOKS_REQUESTED = 'BOOKS_REQUESTED';
const BOOKS_LOADED = 'BOOKS_LOADED';
const BOOKS_LOADING_ERROR = 'BOOKS_LOADING_ERROR';


export {
    BOOKS_REQUESTED,
    BOOKS_LOADED,
    BOOKS_LOADING_ERROR,
}